apiVersion: kustomize.config.k8s.io/v1beta1
resources:
- fv3net/workflows/argo
kind: Kustomization
images:
- name: us.gcr.io/vcm-ml/fv3net
  newTag: 6fc50248c00f9fd8e49034b75a858e233b9d969d
- name: us.gcr.io/vcm-ml/post_process_run
  newTag: 6fc50248c00f9fd8e49034b75a858e233b9d969d
- name: us.gcr.io/vcm-ml/prognostic_run
  newTag: 6fc50248c00f9fd8e49034b75a858e233b9d969d