- name: radiative_fluxes
  config:
    derived_output_variables: 
      - downward_shortwave_sfc_flux_via_transmissivity
      - net_shortwave_sfc_flux_via_transmissivity
    model_type: dense
    random_seed: 0
    cache:
      in_memory: false
      local_download_path: train-data-download-dir
    hyperparameters:
      callbacks:
      - kwargs: {}
        name: WandbCallback
      - kwargs:
          monitor: val_loss
          patience: 15
        name: EarlyStopping
      dense_network:
        depth: 3
        kernel_regularizer:
          kwargs:
            l: 0.0001
          name: l2
        width: 419
      input_variables:
        - cos_zenith_angle
        - surface_geopotential
        - air_temperature
        - specific_humidity
        - latitude
      loss:
        loss_type: mae
        scaling: standard
        weight: 1.0
      normalization_fit_samples: 8000
      normalize_loss: true
      optimizer_config:
        kwargs:
          learning_rate: 0.00014
        name: Adam
      output_variables:
        - shortwave_transmissivity_of_atmospheric_column        
        - override_for_time_adjusted_total_sky_downward_longwave_flux_at_surface
      output_limit_config:
        limits:
          shortwave_transmissivity_of_atmospheric_column:
            min: 0.
            max: 1.
          override_for_time_adjusted_total_sky_downward_longwave_flux_at_surface:
            min: 0.
      save_model_checkpoints: false
      training_loop:
        batch_size: 512
        epochs: 500
        in_memory: true
        shuffle_buffer_size: 50000

